// Generated by Wrangler on Fri Jan 19 2024 07:45:34 GMT-0300 (Brasilia Standard Time)
interface Env {
	assets: KVNamespace;
	__STATIC_CONTENT: KVNamespace;
	ENVIRONMENT: "dev";
	DEFAULT_SITE: "HOST";
	HOST_SITE_URL: "https://app.calligo.com.br";
	GUEST_SITE_URL: "https://site.calligo.com.br";
	FLAREBENDER_URL: "https://dev.calligo.com.br";
	INVITE_ONLY: ["*.calligo.com.br","api.mapbox.com"];
	ASSETS_ROOT_URL: "https://pub-af676e7bac2a43fe933b3cad13657f02.r2.dev";
	ASSETS_ROOT: "./public";
	STATIC_PREFIX: "/flarebender-static";
	BUCKET_NAME: "calligo-dev";
	r2: R2Bucket;
}
