name               = "calligo-flarebender-dev"
main               = "src/worker.ts"
account_id         = "98b1eb8f5ff834b7407343d0a4749e9f"
compatibility_date = "2024-01-16"
workers_dev        = true

[site]
	bucket = "./public"

[dev]
	port              = 8787
	local_protocol    = "https"
	upstream_protocol = "https"
	host              = "dev.calligo.com.br"

[env.dev]
	name = "calligo-flarebender-prod"

	[env.dev.route]
		pattern       = "dev.calligo.com.br"
		zone_name     = "calligo.com.br"
		custom_domain = true

	[[env.dev.r2_buckets]]
		binding             = "r2"
		bucket_name         = "calligo-dev"
		preview_bucket_name = "calligo-dev-preview"

	[env.dev.vars]
		ENVIRONMENT     = "dev"
		DEFAULT_SITE    = "HOST"
		HOST_SITE_URL   = "https://app.calligo.com.br"
		GUEST_SITE_URL  = "https://site.calligo.com.br"
		FLAREBENDER_URL = "https://dev.calligo.com.br"
		INVITE_ONLY     = ["*.calligo.com.br", "api.mapbox.com"]
		ASSETS_ROOT_URL = "https://pub-af676e7bac2a43fe933b3cad13657f02.r2.dev"
		ASSETS_ROOT     = "./public"
		STATIC_PREFIX   = "/flarebender-static"
		BUCKET_NAME     = "calligo-dev"

	[[env.dev.kv_namespaces]]
		binding = "assets"
		id      = "6ba58482c4ee4c5ca1b42e1250ad2451"

	[[env.dev.kv_namespaces]]
		binding = "__STATIC_CONTENT"
		id      = "05e8fbe41d72483389e940b0af11efdd"

[env.prod]
	name = "calligo-flarebender-prod"

	[env.prod.route]
		pattern       = "calligo.com.br"
		zone_name     = "calligo.com.br"
		custom_domain = true

	[env.prod.vars]
		ENVIRONMENT     = "prod"
		DEFAULT_SITE    = "HOST"
		HOST_SITE_URL   = "https://app.calligo.com.br"
		GUEST_SITE_URL  = "https://site.calligo.com.br"
		FLAREBENDER_URL = "https://calligo.com.br"
		INVITE_ONLY     = ["*.calligo.com.br", "api.mapbox.com"]
		ASSETS_ROOT_URL = "https://r2.calligo.com.br"
		ASSETS_ROOT     = "./public"
		STATIC_PREFIX   = "/flarebender-static"
		BUCKET_NAME     = "calligo"

	[[env.prod.kv_namespaces]]
		binding = "assets"
		id      = "246d12a1318446b7bccfc0ba5286e823"

	[[env.prod.kv_namespaces]]
		binding = "__STATIC_CONTENT"
		id      = "13bca2c51789402d8397d9732771e59a"

	[[env.prod.r2_buckets]]
		binding             = "r2"
		bucket_name         = "calligo"
		preview_bucket_name = "calligo-preview"
